# image will be published to ghcr.io/<user>/<name>
name: sericea-main
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr:
          /usr # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
      - nix-installer
      - laptop
      - 1password

  - type: script
    scripts:
      - chezmoi.sh

  - type: rpm-ostree
    repos:
      - https://cli.github.com/packages/rpm/gh-cli.repo
      - https://copr.fedorainfracloud.org/coprs/alternateved/keyd/repo/fedora-%OS_VERSION%/alternateved-keyd-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/bmanuel/python-validity/repo/fedora-%OS_VERSION%/bmanuel-python-validity-fedora-%OS_VERSION%.repo
    install:
      - fish
      - fontawesome-fonts
      - fprintd-clients
      - fprintd-clients-pam
      - gh
      - keyd
      - libadwaita
      - open-fprintd
      - python3-validity
      - starship
    remove:
      - fprintd
      - fprintd-pam

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Noto Sans

  - type: systemd
    system:
      enabled:
        - keyd.service
        - open-fprintd-resume.service
        - open-fprintd-suspend.service
        - open-fprintd.service
        - python3-validity.service
    user:
      enabled:
        - kanshi.service

  - type: script
    scripts:
      - enable-fingerprint.sh
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
